# Numpy 矩阵乘法
> 2022090909003 李晨熙

In [1]:
import numpy as np

### 创建两个80\*60和60\*80的矩阵

In [2]:
matrix_01 = np.zeros((60,80))
matrix_02 = np.zeros((80,60))

### 循环给两个矩阵赋值114514和1919810

In [4]:
a = [1,1,4,5,1,4]
b = [1,9,1,9,8,1,0]
for i in range (60):
    for j in range (80):
        matrix_01[i,j] = a[(i*j)%6]
        matrix_02[j,i] = b[(i*j)%7]
print(matrix_01)
print(matrix_02)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 4. ... 4. 1. 1.]
 [1. 4. 1. ... 1. 1. 4.]
 ...
 [1. 5. 1. ... 5. 1. 5.]
 [1. 1. 4. ... 4. 1. 1.]
 [1. 4. 1. ... 1. 1. 4.]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 9. 1. ... 9. 1. 9.]
 [1. 1. 8. ... 1. 8. 0.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 9. 1. ... 9. 1. 9.]
 [1. 1. 8. ... 1. 8. 0.]]


### 矩阵相乘

In [5]:
result = np.dot(matrix_01,matrix_02)
print(result)

[[ 80. 330. 329. ... 330. 329. 329.]
 [210. 851. 870. ... 851. 870. 878.]
 [161. 675. 650. ... 675. 650. 650.]
 ...
 [240. 994. 985. ... 994. 985. 989.]
 [158. 651. 674. ... 651. 674. 650.]
 [213. 875. 846. ... 875. 846. 878.]]
